#!/usr/bin/with-contenv bash

# make our folders
mkdir -p /config/logs

# populate /config if missing
cp --no-clobber /app/pytivo/pyTivo.conf.dist /config/pyTivo.conf

# permissions
chmod +x /app/pytivo/pyTivo.py
chown -R abc:abc /config
